#lang racket

(require eopl "lang.rkt" "static-data-structures.rkt")
(provide (all-defined-out))

(define check-equal-type!
  (lambda (ty1 ty2 exp)
    (when (not (equal? ty1 ty2))
      (display (format "Types didn't match: ~a != ~a in ~a~%"
                       (type-to-external-form ty1)
                       (type-to-external-form ty2)
                       exp))
      (error 'error-occurred))))

(define type-of
  (lambda (exp tenv)
    (cases expression exp
      (const-exp (num) (int-type))
      (var-exp (var) (apply-tenv tenv var))
      (qualified-var-exp (m-name var-name)
        (lookup-qualified-var-in-tenv m-name var-name tenv))
      (diff-exp (exp1 exp2)
        (let ((ty1 (type-of exp1 tenv))
              (ty2 (type-of exp2 tenv)))
          (check-equal-type! ty1 (int-type) exp1)
          (check-equal-type! ty2 (int-type) exp2)
          (int-type)))
      (zero?-exp (exp)
        (let ((ty1 (type-of exp tenv)))
          (check-equal-type! ty1 (int-type) exp)
          (bool-type)))
      (if-exp (exp1 exp2 exp3)
        (let ((ty1 (type-of exp1 tenv))
              (ty2 (type-of exp2 tenv))
              (ty3 (type-of exp3 tenv)))
          (check-equal-type! ty1 (bool-type) exp1)
          (check-equal-type! ty2 ty3 exp)
          ty2))
      (let-exp (var exp body)
        (let ((exptype (type-of exp tenv)))
          (type-of body (extend-tenv var exptype tenv))))
      (proc-exp (var var-type body)
        (let* ((new-tenv (extend-tenv var var-type tenv))
               (body-type (type-of body new-tenv)))
          (proc-type var-type body-type)))
      (call-exp (rator rand)
        (let ((rator-type (type-of rator tenv))
              (rand-type (type-of rand tenv)))
          (cases type rator-type
            (proc-type (arg-type result-type)
              (begin
                (check-equal-type! arg-type rand-type rand)
                result-type))
            (else (error 'not-a-procedure)))))
      (letrec-exp (p-result-type p-name b-var b-var-type p-body letrec-body)
        (let* ((expected-proc-type (proc-type b-var-type p-result-type))
               (body-tenv (extend-tenv p-name expected-proc-type tenv))
               (proc-tenv (extend-tenv b-var b-var-type body-tenv))
               (real-body-type (type-of letrec-body body-tenv))
               (real-proc-result-type (type-of p-body proc-tenv)))
          (check-equal-type! real-proc-result-type p-result-type p-body)
          real-body-type))
      (else (error 'unexpected-exp)))))

;(define test
;  (lambda (text)
;    (cases program (scan&parse text)
;      (a-program (mds exp)
;        (type-of exp (test-tenv))))))
